
runtime: php55

handlers:
- url: /styles
  static_dir: assets/styles

- url: /image/(.*\.(gif|png|jpg))
  static_files: assets/image/\1
  upload: image/(.*\.(gif|png|jpg))

- url: /.*
  script: index.php
