
runtime: php55

handlers:
- url: /styles
  static_files: assets/styles/style.css
  upload: assets/styles/style.css

- url: /image/(.*\.(gif|png|jpg))
  static_files: assets/image/\1
  upload: image/(.*\.(gif|png|jpg))

- url: /.*
  script: index.php
